// apps/student-portal/app/login/UserButton.tsx
import React, { useState } from 'react';
import { Avatar } from 'primereact/avatar';
import { Button } from 'primereact/button';
import { Menu } from 'primereact/menu';
import { useRouter } from 'next/navigation';
import { useAuth } from './useAuth';

interface UserButtonProps {
    size?: 'default' | 'small';
}

export default function UserButton({ size = 'default' }: UserButtonProps) {
    const [menuVisible, setMenuVisible] = useState(false);
    const menuRef = React.useRef<Menu>(null);
    const router = useRouter();
    const { user, signOut } = useAuth();

    const menuItems = user
        ? [
              {
                  label: user.email
                      ? user.email.length > 15
                          ? user.email.substring(0, 15) + '...'
                          : user.email
                      : 'User email',
                  disabled: true,
              },
              {
                  label: 'Sign Out',
                  icon: 'pi pi-sign-out',
                  command: () => signOut(),
              },
          ]
        : [];

    if (!user) {
        return (
            <Button
                onClick={() => router.push('/user/create')}
                label={size === 'default' ? 'Register / Sign In' : 'Account'}
                className="p-button-md"
            />
        );
    }

    return (
        <div className="cursor-pointer">
            <Avatar
                size="large"
                icon="pi pi-user"
                onClick={(e) => menuRef.current?.toggle(e)}
                className="mr-2"
                style={{
                    backgroundColor: '#aaa',
                    color: '#ffffff',
                }}
            />
            <Menu
                ref={menuRef}
                popup
                model={menuItems}
                onShow={() => setMenuVisible(true)}
                onHide={() => setMenuVisible(false)}
            />
        </div>
    );
}

// libs/auth/login/src/lib/components/user-button.component.ts
import { CommonModule } from '@angular/common';
import {
    ChangeDetectionStrategy,
    Component,
    inject,
    Input,
    OnInit,
} from '@angular/core';
import { UserService } from '@sol/auth/user';
import { AuthService } from '@sol/firebase/auth';
import { MenuItem } from 'primeng/api';
import { AvatarModule } from 'primeng/avatar';
import { ButtonModule } from 'primeng/button';
import { MenuModule } from 'primeng/menu';
import { map, Observable } from 'rxjs';

@Component({
    standalone: true,
    changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [
        CommonModule,
        MenuModule,
        AvatarModule,
        ButtonModule,
        AuthService,
    ],
    selector: 'sol-user-button',
    template: ` <ng-container *ngIf="email$ | async as email; else login">
            <div style="cursor: pointer">
                <p-avatar
                    size="large"
                    icon="pi pi-user"
                    (click)="menu.toggle($event)"
                    styleClass="mr-2"
                    [style]="{
                        'background-color': '#aaa',
                        color: '#ffffff'
                    }"
                ></p-avatar>
                <p-menu
                    #menu
                    [popup]="true"
                    [model]="(menuItems$ | async) ?? []"
                ></p-menu>
            </div>
        </ng-container>
        <ng-template #login>
            <p-button
                routerLink="/user/create"
                [label]="size === 'default' ? 'Register / Sign In' : 'Account'"
                styleClass="p-button-md"
            ></p-button
        ></ng-template>`,
})
export class UserButtonComponent implements OnInit {
    private readonly auth = inject(AuthService);
    private readonly userService = inject(UserService);

    @Input() size: 'default' | 'small' = 'default';

    public email$: Observable<string | null | undefined> | undefined;

    public menuItems$: Observable<Array<MenuItem>> = this.userService
        .getUser()
        .pipe(
            map((user) => [
                {
                    label:
                        (user?.email?.substring(0, 15) ?? 'User email') +
                        (user?.email?.length ?? 0 > 15 ? '...' : ''),
                    disabled: true,
                },
                {
                    label: 'Enrollments',
                    routerLink: '/account/enrollments',
                },
                {
                    label: 'Manage Account',
                    routerLink: '/account/manage',
                },
                {
                    label: 'Sign Out',
                    icon: 'pi pi-sign-out',
                    command: () => this.signOut(),
                },
            ])
        );

    ngOnInit() {
        this.email$ = this.userService
            .getUser()
            .pipe(map((user) => user?.email));
    }

    signOut() {
        this.auth.logout();
    }
}
