// libs/header/src/lib/components/header.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterModule } from '@angular/router';
import { UserButtonComponent } from '@sol/auth/login';
import { UserService } from '@sol/auth/user';
import { ButtonModule } from 'primeng/button';
import { SidebarModule } from 'primeng/sidebar';
import { ToolbarModule } from 'primeng/toolbar';

@Component({
    standalone: true,
    changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [
        CommonModule,
        ButtonModule,
        SidebarModule,
        ToolbarModule,
        RouterModule,
        UserButtonComponent,
    ],
    styles: [
        `
            .toolbar {
                color: green;
            }
        `,
    ],
    template: ` <header class="toolbarz">
            <p-toolbar styleClass="toolbar">
                <div routerLink="/" class="p-toolbar-group-left">
                    <div>
                        <img
                            src="https://www.mountainsol.org/wp-content/uploads/2020/03/SOL-horizontal-large-1024x234-1.jpg"
                            alt="sol-logo"
                            height="50px"
                            style="margin-right:10px"
                        />
                    </div>
                    <h2 style="margin: 0; cursor: pointer">
                        Registration Portal
                    </h2>
                </div>
                <div class="p-toolbar-group-right">
                    <ng-container
                        *ngIf="(isLoggedIn$ | async) && (isAdmin$ | async)"
                    >
                        <div style="margin-right: 2rem">
                            <p-button
                                type="text"
                                (click)="display = true"
                                icon="pi pi-bars"
                                label="Menu"
                            ></p-button></div
                    ></ng-container>
                    <sol-user-button></sol-user-button>
                </div>
            </p-toolbar>
        </header>
        <div style="padding: 1rem"><router-outlet></router-outlet></div>
        <p-sidebar [(visible)]="display" position="right">
            <ul style="font-size:16px">
                <li>
                    <a routerLink="/admin/report" (click)="display = false"
                        >Class Forms and Contacts</a
                    >
                </li>
                <li>
                    <a routerLink="/admin/t-shirts" (click)="display = false"
                        >Tshirt Sizes</a
                    >
                </li>
                <li>
                    <a routerLink="/calendar/classes" (click)="display = false"
                        >Class Calendar</a
                    >
                </li>
                <li>
                    <a
                        routerLink="/classes/enrollment"
                        (click)="display = false"
                        >Class Registration</a
                    >
                </li>
            </ul>
        </p-sidebar>`,
})
export class HeaderComponent {
    private readonly userService = inject(UserService);

    display = false;

    window = window;

    isLoggedIn$ = this.userService.isLoggedIn();
    isAdmin$ = this.userService.isAdmin();
}

// apps/student-portal/components/Header.tsx
'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import { Toolbar } from 'primereact/toolbar';
import { Button } from 'primereact/button';
import { Sidebar } from 'primereact/sidebar';
import { useMediaQuery } from 'react-responsive';
import UserButton from '../app/login/UserButton';
import { useAuth } from '../app/login/useAuth';

const Header = () => {
    const [display, setDisplay] = useState(false);
    const isDefault = useMediaQuery({ minWidth: 600 });
    const router = useRouter();
    const { isLoggedIn, isAdmin } = useAuth();

    const leftContents = (
        <div
            className="flex items-center cursor-pointer p-toolbar-group-left"
            onClick={() => router.push('/')}
        >
            <Image
                src="https://www.mountainsol.org/wp-content/uploads/2020/03/SOL-horizontal-large-1024x234-1.jpg"
                alt="sol-logo"
                width={isDefault ? 218 : 153}
                height={isDefault ? 50 : 35}
                className="mr-2"
            />
            <h2 className="m-0">{isDefault ? 'Student Portal' : 'Portal'}</h2>
        </div>
    );

    const rightContents = (
        <div className="flex items-center gap-4">
            {isLoggedIn && isAdmin && (
                <Button
                    icon="pi pi-bars"
                    label="Menu"
                    onClick={() => setDisplay(true)}
                />
            )}
            <UserButton size={isDefault ? 'default' : 'small'} />
        </div>
    );

    return (
        <>
            <Toolbar start={leftContents} end={rightContents} />

            <Sidebar
                visible={display}
                position="right"
                onHide={() => setDisplay(false)}
            >
                <ul className="text-base">
                    <li>
                        <a
                            href="https://enrollment.mountainsol.org/classes/enrollment"
                            onClick={() => setDisplay(false)}
                        >
                            Class Registration
                        </a>
                    </li>
                    <h4 className="font-semibold mt-4 mb-1">Admin</h4>
                    <li>
                        <a
                            href="https://enrollment.mountainsol.org/admin"
                            onClick={() => setDisplay(false)}
                        >
                            Dashboard
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://enrollment.mountainsol.org/admin/report"
                            onClick={() => setDisplay(false)}
                        >
                            Class Forms and Contacts
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://enrollment.mountainsol.org/admin/t-shirts"
                            onClick={() => setDisplay(false)}
                        >
                            T-shirt Sizes
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://enrollment.mountainsol.org/admin/enrollments"
                            onClick={() => setDisplay(false)}
                        >
                            Enrollments
                        </a>
                    </li>
                    <li>
                        <a
                            href="https://enrollment.mountainsol.org/calendar/classes"
                            onClick={() => setDisplay(false)}
                        >
                            Class Calendar
                        </a>
                    </li>
                    <li>
                        <a href="/units" onClick={() => setDisplay(false)}>
                            Student Units
                        </a>
                    </li>
                </ul>
            </Sidebar>
        </>
    );
};

export default Header;
